// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrDoiG7OgS9u6FluKjaEHYJIbmBEAC5yg',
    appId: '1:999107817460:web:421e85fa8f6aa29bf453a1',
    messagingSenderId: '999107817460',
    projectId: 'mynews-93127',
    authDomain: 'mynews-93127.firebaseapp.com',
    storageBucket: 'mynews-93127.appspot.com',
    measurementId: 'G-LKW4M0DZWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdGw1k4459hrdC0gbq3GTzzJUuhJqtenQ',
    appId: '1:999107817460:android:c617e4c75a6a36faf453a1',
    messagingSenderId: '999107817460',
    projectId: 'mynews-93127',
    storageBucket: 'mynews-93127.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtRPHwa9Px5jvaF6puxW_QJBhUT8ds0F0',
    appId: '1:999107817460:ios:fd26202070cb4739f453a1',
    messagingSenderId: '999107817460',
    projectId: 'mynews-93127',
    storageBucket: 'mynews-93127.appspot.com',
    iosBundleId: 'com.example.mynews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtRPHwa9Px5jvaF6puxW_QJBhUT8ds0F0',
    appId: '1:999107817460:ios:fd26202070cb4739f453a1',
    messagingSenderId: '999107817460',
    projectId: 'mynews-93127',
    storageBucket: 'mynews-93127.appspot.com',
    iosBundleId: 'com.example.mynews',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrDoiG7OgS9u6FluKjaEHYJIbmBEAC5yg',
    appId: '1:999107817460:web:17180a00ba2c13b7f453a1',
    messagingSenderId: '999107817460',
    projectId: 'mynews-93127',
    authDomain: 'mynews-93127.firebaseapp.com',
    storageBucket: 'mynews-93127.appspot.com',
    measurementId: 'G-8TE4T42VVH',
  );
}
